OLshop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('main.urls')),
    path('api/books/', include('book.urls')),
    path('product_page/', include('product_page.urls')),
    path('cart/', include('cart.urls')),
    path('leaderboard/', include('leaderboard.urls')),
    path('checkout/', include('checkout.urls')),
    path('review/', include('review.urls')),
    path('auth/', include('authentication.urls')),
]

book/urls.py
from django.urls import path
from main.views import show_main
from book.views import get_books

app_name = "book"
urlpatterns = [
    path("", get_books, name="get_books"),
]

leaderboard/urls.py
from django import views
from django.urls import path
from .views import  show_leaderboard, get_product_json, search_bar, create_comment
from .views import show_xml, show_json, show_xml_by_id, show_json_by_id, create_comment_flutter, get_leaderboard_flutter, get_comment_flutter 




app_name = 'leaderboard'

urlpatterns = [
    # path('', show_leaderboard),
    path('', show_leaderboard, name='show_leaderboard'),
    path('get_product_json/', get_product_json, name='get_product_json'),
    path('search_bar/<str:value>', search_bar, name='search_bar'),
    path('create_comment', create_comment, name='create_comment'),
    path('xml/', show_xml, name='show_xml'), 
    path('json/', show_json, name='show_json'), 
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'),
    path('create_comment_flutter/', create_comment_flutter, name='create_comment_flutter'),
    path('get_leaderboard_flutter/', get_leaderboard_flutter, name='get_leaderboard_flutter'),
    path('get_comment_flutter/', get_comment_flutter, name='get_comment_flutter'),
]

leaderboard/models.py
from django.db import models
from book.models import Book
from django.contrib.auth.models import User

class LeaderBoard(models.Model):
    users = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    # quote = models.TextField(default = "")
    book = models.ForeignKey(Book, on_delete=models.CASCADE, default=None)
class Comment(models.Model):
    comment = models.CharField(max_length=255)

leaderboard/forms.py
from django.forms import ModelForm
from leaderboard.models import Comment

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ["comment"]

leaderboard/views.py
from datetime import datetime
import json
from django.http import HttpResponse
from django.shortcuts import render
from requests import request
from book.models import Book
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages 
from django.shortcuts import redirect 
from django.contrib.auth.forms import UserCreationForm
# Create your views here.
from django.core import serializers
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponseNotFound
from django.http import HttpResponseRedirect
# from leaderboard.forms import ProductForm
from django.urls import reverse
from leaderboard.models import LeaderBoard, Comment
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from leaderboard.forms import CommentForm
from django.urls import reverse
from django.http import HttpResponse
from django.core import serializers
from django.http import HttpResponseNotFound, HttpResponseRedirect, JsonResponse


from django.shortcuts import render 
from book.models import Book


def show_xml_by_id(request, id):
    data = Comment.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")


def show_json_by_id(request, id):
    data = Comment.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")



def show_xml(request):
    data = Comment.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Comment.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

@login_required(login_url='/login')
def show_leaderboard(request):
    # Get the last time the leaderboard page was opened from the cookie
    last_opened = request.COOKIES.get('last_opened', None)
    context = {
        'last_opened': last_opened,
        'comments': Comment.objects.all(),
        'name': request.user.username,
        'last_login': request.user.last_login,
    }
    # Update the cookie with the current timestamp
    response = render(request, "leaderboard.html", context=context)
    response.set_cookie('last_opened', datetime.now().strftime("%Y-%m-%d %H:%M:%S.%f"))
    
    # Display the last time the leaderboard page was opened
    try:
        if last_opened:
            last_opened = datetime.strptime(last_opened, "%Y-%m-%d %H:%M:%S.%f")
        else:
            last_opened = datetime.min  # Set to the minimum datetime value to indicate "N/A"
    except ValueError:
        # Handle the case where the 'last_opened' cookie has an unexpected format
        last_opened = datetime.min  # Set to the minimum datetime value to indicate "N/A"

    
    return response

def get_product_json(request):
    product_item = Book.objects.all()
    return HttpResponse(serializers.serialize('json', product_item))

def search_bar(request, value):
    product_item = Book.objects.filter(title__icontains=value)
    print(serializers.serialize('json', product_item))
    return HttpResponse(serializers.serialize('json', product_item))

def create_comment(request):
    form = CommentForm(request.POST or None)
    if form.is_valid() and request.method == "POST":
        form.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "create_comment.html", context)


def get_leaderboard_flutter(request):
    product_items = Book.objects.all().order_by('-buys')

    # Serialize the sorted products to JSON
    json_data = serializers.serialize('json', product_items)

    # Return the JSON response
    return JsonResponse(json_data, safe=False, status=200)


@csrf_exempt
def create_comment_flutter(request):
    if request.method == 'POST':
        msg = json.loads(request.body)['comment']

        comment = Comment.objects.create(comment=msg).save()
        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

@csrf_exempt
def get_comment_flutter(request):
    comment_items=Comment.objects.all()
    json_data = serializers.serialize('json', comment_items)
    # return HttpResponse(json_data, content_type="application/json")
    return JsonResponse(json_data, safe=False, status=200)

leaderboard/templates/create_comment.html
{% extends 'base.html' %} 

{% block content %}
<h1>Add New Product</h1>

<form method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
        <tr>
            <td></td>
            <td>
                <input type="submit" value="Add Comment" href="leaderboard/"/>
            </td>
        </tr>
    </table>
</form>

{% endblock %}

leaderboard/templates/leaderboard.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<body class="font-sans bg-gray-200">
  <nav class="navbar navbar-expand-lg custom-navbar-bg">
    <div class="container-fluid">
      <button class="button-product-page">
        <img src="https://raw.githubusercontent.com/kayzaazr/cupcat-shop/main/gambar-website/BukuKu..png" class="logobuku"> 
    </button>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav" style="margin-left: 500px">
                <li class="nav-item">
                    <a class="nav-link active" style="font-family: Amiko-Regular, Helvetica;font-size: 20px; color: #71C78F;margin-right: 10px;" aria-current="page" href="/">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" style="font-family: Amiko-Regular, Helvetica;font-size: 20px; color: #71C78F; margin-right: 10px; margin-left: 10px;" href="/product_page">Product Page</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" style="font-family: Amiko-Regular, Helvetica;font-size: 20px; color: #71C78F;margin-right: 10px; margin-left: 10px;" href="/leaderboard/">Product Leaderboard</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" style="font-family: Amiko-Regular, Helvetica;font-size: 20px; color: #71C78F;margin-right: 10px; margin-left: 10px;" href="/cart/">
                    <img src="https://github.com/MahogaHeryasa/temp/blob/master/IMG/Group%2059.png?raw=true"/>
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" style="font-family: Amiko-Regular, Helvetica;font-size: 20px; color: #71C78F;margin-right: 10px; margin-left: 10px;" href="">{{name}}</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
    <p>Sesi sebelumnya leaderboard dibuka: {{ last_opened }}</p>
    <div class="bg-white p-5 flex items-center justify-between">
      <input oninput="filter(this)" type="text" placeholder="Cari buku Anda..." class="flex-grow border rounded-lg p-2 text-white" style="background-color:#71C78F; " placeholder="Search">
    </div>

    <div class="p-5 bg-white">
      <h1 class="text-2xl my-5">LeaderBoard</h1>
      <table id="product_table" class="w-full">
      </table>
    </div>

    <table style="align-items: center; text-align: center;" id="comment_table"></table>
      <tr style="background-color: #71C78F">
        <th>Comment Section</th>
      </tr>

      {% comment %} Berikut cara memperlihatkan data produk di bawah baris ini {% endcomment %}

      {% for comment in comments %}
      <tr>
        <td>{{ comment.comment }}</td>
      </tr>
      {% endfor %}
    </table>

    <br />

    <a href="{% url 'leaderboard:create_comment' %}">
      <button>
        Add New Comment
      </button>
    </a>

    <script src="{% static 'js/leaderboard.js' %}"></script>
    <script>
      async function getProducts() {
    try {
        const response = await fetch("{% url 'leaderboard:get_product_json' %}");
        if (!response.ok) {
        throw new Error(`HTTP error! Status: ${response.status}`);
        }
        
        const products = await response.json();
        
        // Sort the products by the 'buys' attribute in ascending order
        products.sort((a, b) => a.buys - b.buys);
        
        return products;
    } catch (error) {
        console.error("Error fetching and sorting products:", error);
        throw error;
    }
}


async function refreshProducts() {
    document.getElementById("product_table").innerHTML = ""
    const products = await getProducts()
    products.sort((a, b) => b.buys - a.buys);
    let htmlString = `<tr>
        <th>Rank</th>
        <th>Title</th>
        <th>Price</th>
        <th>Author</th>
        <th>Stars</th>
        <th>Buys</th>
    </tr>`
    var rank = 0
    products.forEach((item) => {
        rank +=1
        htmlString += `\n<tr>
        <td>${rank}</td>
        <td>${item.fields.title}</td>
        <td>${item.fields.price}</td>
        <td>${item.fields.author}</td>
        <td>${item.fields.stars}</td>
        <td>${item.fields.buys}</td>
    </tr>` 
    })


    document.getElementById("product_table").innerHTML = htmlString
}

refreshProducts()

async function filter(input){
document.getElementById("product_table").innerHTML = ""
    const products = await getProducts()
    products.sort((a, b) => b.buys - a.buys);
    let htmlString = `<tr>
        <th>Rank</th>
        <th>Title</th>
        <th>Price</th>
        <th>Author</th>
        <th>Stars</th>
        <th>Buys</th>
    </tr>`
    var rank = 0
    products.forEach((item) => {
        rank +=1
        if(item.fields.title.toLowerCase().includes(input.value.toLowerCase())){
        htmlString += `\n<tr>
        <td>${rank}</td>
        <td>${item.fields.title}</td>
        <td>${item.fields.price}</td>
        <td>${item.fields.author}</td>
        <td>${item.fields.stars}</td>
        <td>${item.fields.buys}</td>
        </tr>` 
        }
        
    })


    document.getElementById("product_table").innerHTML = htmlString
}
    </script>

</body>
{% endblock %}