OLshop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('main.urls')),
    path('api/books/', include('book.urls')),
    path('product_page/', include('product_page.urls')),
    path('cart/', include('cart.urls')),
    path('leaderboard/', include('leaderboard.urls')),
    path('checkout/', include('checkout.urls')),
    path('review/', include('review.urls')),
    path('auth/', include('authentication.urls')),
]

book/urls.py
from django.urls import path
from main.views import show_main
from book.views import get_books

app_name = "book"
urlpatterns = [
    path("", get_books, name="get_books"),
]

product_page/urls.py
from django.urls import path
from .views import *

app_name = 'product_page'

urlpatterns = [
    path('', show_product, name='show_product'),
    path('get_product_json/', get_product_json, name='get_product_json'),
    path('add_to_cart', add_cart, name='add_cart'),
    path('search_bar/<str:value>', search_bar, name='search_bar'),
    path('search_bar2/<str:value>', search_bar2, name='search_bar2'),
    path('add_cart_flutter/', add_cart_flutter, name='add_cart_flutter')
]

product_page/models.py
from django.db import models
from book.models import Book

class Product(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    last_added_to_cart = models.DateField(auto_now_add=True)

product_page/views.py
from datetime import date
import json
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render
from book.models import Book
from django.core import serializers
from cart.models import Cart
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from product_page.models import Product
from django.contrib.auth import get_user_model


# Create your views here.
@login_required(login_url='/login')
def show_product(request):
    books = Book.objects.all()
    context = {
        'books' : books
    }

    return render(request, "product_page.html", context)

def get_product_json(request):
    product_item = Book.objects.all()
    return HttpResponse(serializers.serialize('json', product_item))


@csrf_exempt
def add_cart(request):
    
    body = json.loads(
        request.body.decode('utf-8'))
    
    id = body['id']
    
    # product = Product(last_added_to_cart = date.today())
    # product.save()
    
    book = Book.objects.get(pk=id)
    if(Cart.objects.filter(user = request.user.id, book_id= id)):
        cart = Cart.objects.get(user = request.user.id, book_id = id)
        cart.book_amount += 1
        cart.save()
        return HttpResponse(b"ADDED", status=201)
    else:
        Cart(user = request.user, book = book, book_amount = 1).save()
        return HttpResponse(b"ADDED", status=201)

def search_bar(request, value):
    product_item = Book.objects.filter(title__icontains=value)
    print(serializers.serialize('json', product_item))
    return HttpResponse(serializers.serialize('json', product_item))

def search_bar2(request, value):
    product_item = Book.objects.filter(author__icontains=value)
    print(serializers.serialize('json', product_item))
    return HttpResponse(serializers.serialize('json', product_item))

UserModel = get_user_model()
@csrf_exempt
def add_cart_flutter(request):
    if request.method == 'POST':
        body = json.loads(request.body)
        book_id = body['id']
        if book_id is not None:
                book = Book.objects.get(pk=book_id)
                user_id = body['user_id']
                if Cart.objects.filter(user=user_id, book_id=book_id).exists():
                    cart_item = Cart.objects.get(user=user_id, book_id=book_id)
                    cart_item.book_amount += 1
                    cart_item.save()
                else:
                    Cart.objects.create(user=UserModel.objects.get(id=user_id), book=book, book_amount=1)
                return JsonResponse({"status": "ADDED"}, status=201)
        else:
            return JsonResponse({"status": "Invalid request"}, status=400)

product_page/templates/product_page.html
{% extends 'base.html' %} 
{% load static %}
{% block content %}
<head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <style>
        .card {
            display: flex;
            color: #0A3100;
            text-align: center;
            font-style: normal;
            font-weight: 400;
            line-height: normal;
            width: 215.097px;
            min-height:390.582px;
            justify-content: space-between;
            align-items: center;
            border-radius: 12.997px;
            background: #FFF;
            border: 5px solid #79C278;
            box-shadow: 3.2492px 3.2492px 12.99679px 0px rgba(0, 0, 0, 0.25);
            gap:4.95px;
            padding: 10px;
        }

        .image-book {
            justify-content: center;
            align-items: center;
            height: auto;
            width:65%;
            margin-top: 5px;
        }

        #title {
            width: 100%;
            flex-direction: row;
            flex-wrap: wrap;
            display: flex;
            align-items: center;
            justify-content: center;
            gap:20.79px;
        }

        .judul-buku {
            width:90%;
            overflow: hidden;
            text-overflow: ellipsis;
            white-space: nowrap;
        }

        .button-all {
            display: flex;
            flex-shrink: row;
        }


        .input-search {
            display: flex;
            align-items: center;
            justify-content: center;
            border-radius: 10px;
            padding-left: 20px;
            border:hidden;
            color: white;
            background: #79C278;
            box-shadow: 0px 4px 20px 0px rgba(0, 0, 0, 0.25) inset;
            width: 1052px;
            height: 40px;
            
        }

        .input-search::placeholder{
            color: white;
        }

        .isi-content {
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            gap:30px;
        }

    
        .button-all {
            display: flex;
            flex-direction: row;
            gap:7px;
            
        }

        .navbarbuku {
            display: flex;
            flex-direction: row;
            justify-content: space-between;
            width: 100%;

        }

        .search-filter-bar {
            display: flex;
            align-items: center;
            justify-content: center;
            gap: 5px;
        }

        .dropbtn {
            background: transparent; 
            border: none; 
            padding: 0; 
            margin: 0;
        }
        
        .dropdown {
            position: relative;
            display: inline-block;
        }
        
        .dropdown-content {
            display: none;
            position: absolute;
            background-color: #f1f1f1;
            min-width: 160px;
            box-shadow: 0px 8px 16px 0px rgba(0, 0, 0, 0.2);
            z-index: 1;
            flex-direction: column; 
            border: 1px solid #ccc;
            border-radius: 4px;
        }
        
        .dropdown-content button {
            padding: 10px; 
            width: 200px;

            text-align: left; 
            background-color: transparent;
            border: none;
            cursor: pointer;
        }


        .dropdown-content button:hover {
            background-color: #ddd;
        }
        .dropdown-content a:hover {background-color: #ddd;}
    
        .dropdown:hover .dropdown-content {display: block;}

        .button-cart {
            background: transparent; 
            border: none; 
            padding: 0; 
            margin: 0;
            margin-right:40px;
            margin-top: 10px;

        } 

        .filter-img {
            width: 75%; 
            height: auto;
        }


        .logobuku {
            width: 85%;
            height: 50%;
            margin-left:1px;
            margin-top: 30px;
        }
        
        .rate-buku {
            display: flex;
            margin-left: 0;
        }

        .harga-buku {
            color: #33B031;
        }

        .button-product-page {
            background: transparent; 
            border: none; 
            padding: 0; 
            margin: 0;
            margin-left:40px;
            margin-top: 10px;
        }

        .navbar {
            background-color: #3498db; 
        }
        
        .navbar-toggler {
            background-color: #fff; 
            border: none; 
        }
        
        .nav-link {
            color: #33B031; 
            margin: 0 10px; 
        }
 
        .button-cart {
            background-color: transparent;
            color: #33B031; 
            border: none; 
            padding: 5px 10px; 
            border-radius: 5px; 
        }

        .button-cart-img {
            width: 20px; 
            height: 20px; 
            margin-right: 1px; 
            margin-top: 10px;
        }

        .review-page-button {
            color: #408558;
            background-color: white;
            border: hidden
        }
        
        
    </style>
</head>

<body style="display:flex; flex-direction:column; align-items:center;">
    <div class="toast" id="cartToast" role="alert" aria-live="assertive" aria-atomic="true" data-autohide="true" data-delay="500" style="position:fixed; z-index: 1; margin-top:18px; max-width:1200px">

    </div>   
    
    <div class="toast" id="searchTitleToast" role="alert" aria-live="assertive" aria-atomic="true" data-autohide="true" data-delay="500" style="position:fixed; z-index: 1; margin-top:18px; width:fit-content">
    </div>   

    <div class="toast" id="searchAuthorToast" role="alert" aria-live="assertive" aria-atomic="true" data-autohide="true" data-delay="500" style="position:fixed; z-index: 1; margin-top:18px; width:fit-content">
    </div>  

    <div class="isi-content">
        <div class="navbarbuku">
            <a href="/product_page">
                <button class="button-product-page">
                    <img src="https://raw.githubusercontent.com/kayzaazr/cupcat-shop/main/gambar-website/BukuKu..png" class="logobuku"> 
                </button>
            </a>
                <nav class="navbar navbar-expand-lg " style="background-color: white;">
                    <div class="container-fluid">
                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse" id="navbarSupportedContent">
                            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                                <li class="nav-item">
                                    <a class="nav-link" aria-current="page" href="/#">Home</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="/product_page">Product Page</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="/leaderboard/">Product Leaderboard</a>
                                </li>
                                <img src="https://raw.githubusercontent.com/kayzaazr/cupcat-shop/main/gambar-website/Mask%20group.png" class="button-cart-img">
                                <li class="nav-item">
                                    <a class="nav-link" href="/cart"> My Cart </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" style="font-family: Amiko-Regular, Helvetica;font-size: 20px; color: #71C78F;margin-right: 10px; margin-left: 10px;" href="">{{name}}</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </nav>
            
        </div>

        <div class="search-filter-bar">
            <input id="search-bar" onkeydown='javascript:test(this)' type="text" placeholder="Cari buku Anda berdasarkan judul..." class="input-search">
            <div class="dropdown">
                <button class="dropbtn"> <img src="https://raw.githubusercontent.com/kayzaazr/cupcat-shop/main/gambar-website/Mask%20group-1.png" class="filter-img"></button>
                <div class="dropdown-content">
                    <button id="button-1" onclick="searchByTitle()" >Cari berdasarkan judul</button>
                    <button id="button-2" onclick="searchByAuthor()">Cari berdasarkan author</button>
                </div>
            </div>
        </div>
        <div id="title"></div>
    </div>
</body>


<script>
    async function refreshProduct() {
        const buku = document.getElementById("title");
        
        const product = await getProduct();
        
        let bukuString = ``
        product.forEach((item) => {
            bukuString += `
             <div class="card">
                <img class="image-book" src="${item.fields.imgUrl}">
                <div class="judul-buku" style="font-family: 'Amiko', sans-serif; font-size: 15px; font-weight: 600"> ${item.fields.title} </div>
                <div class="author-buku"> Written by ${item.fields.author} </div>
                <div class="harga-buku"> Rp${Math.ceil(item.fields.price*15000).toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",")} </div>
                <form action='javascript:add_to_cart(${item.pk})' id='transactionIDValue' class="d-inline" method="post">
                    {{cart_product_form}}
                    {% csrf_token %}
                    <input type="submit" data-toggle="modal" data-target="#moreinfo" class="btn btn-success" value="Add To Cart">
                </form>
                <a href="/review/${item.pk}">
                    <button class="review-page-button"> Review </button> 
                </a>
             </div>`

        })
        buku.innerHTML = bukuString
    }
    
    async function getProduct() {
        
        return fetch("{% url 'product_page:get_product_json' %}").then((res) => res.json())
    }

    refreshProduct()

    async function add_to_cart(book_id) {
        const product = await getProduct();

        product.forEach((item) => {
            if (item.pk == book_id){
                document.getElementById('cartToast').innerHTML = `

                <div class="toast-header">
                    <strong class="mr-auto">Berhasil Menambahkan ${item.fields.title} </strong>
                        <span aria-hidden="true"></span>
                </div>
              `
            }
        })
        
        $('#cartToast').toast('show');
        return fetch(`add_to_cart`, {method:'POST', body:JSON.stringify({id:book_id}), headers: { 'Content-type':'application/json; charset=UTF-8',}}).then((res) => res.json()) 
    }

    async function test(input){
        console.log(input.value)
        const buku = document.getElementById("title");
        let product;
        if (document.getElementById('search-bar').placeholder=="Cari buku Anda berdasarkan judul..."){
            product = await fetch(`search_bar/${input.value}`).then((res) => res.json());
        } else {
            product = await fetch(`search_bar2/${input.value}`).then((res) => res.json());
        }
        
        let bukuString = ``
        product.forEach((item) => {
            bukuString += `
             <div class="card">
                <img class="image-book" src="${item.fields.imgUrl}">
                <div class="judul-buku" style="font-family: 'Amiko', sans-serif; font-size: 15px; font-weight: 600"> ${item.fields.title} </div>
                <div class="author-buku"> Written by ${item.fields.author} </div>
                <div class="harga-buku"> Rp${Math.ceil(item.fields.price*15000).toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",")} </div>
                <form action='javascript:add_to_cart(${item.pk})' id='transactionIDValue' class="d-inline" method="POST">
                    {{cart_product_form}}
                    {% csrf_token %}
                    <input type="submit" data-toggle="modal" data-target="#moreinfo" class="btn btn-success" value="Add To Cart">
                </form>
                <a href="/review/${item.pk}">
                    <button class="review-page-button"> Review </button> 
                </a>

             </div>`

        })
        buku.innerHTML = bukuString
    }

    async function searchByAuthor(){
        document.getElementById('search-bar').placeholder="Cari buku Anda berdasarkan author..."
        document.getElementById('searchAuthorToast').innerHTML = `
                <div class="toast-header">
                    <strong class="mr-auto"> Mencari berdasarkan author.. </strong>
                        <span aria-hidden="true"></span>
                </div>
              `
              $('#searchAuthorToast').toast('show');
    }

    async function searchByTitle(){
        document.getElementById('search-bar').placeholder="Cari buku Anda berdasarkan judul..."
        document.getElementById('searchTitleToast').innerHTML = `
                <div class="toast-header">
                    <strong class="mr-auto"> Mencari berdasarkan judul.. </strong>
                        <span aria-hidden="true"></span>
                </div>
              `
              $('#searchTitleToast').toast('show');

    }

    

</script>
{% endblock %}