OLshop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('main.urls')),
    path('api/books/', include('book.urls')),
    path('product_page/', include('product_page.urls')),
    path('cart/', include('cart.urls')),
    path('leaderboard/', include('leaderboard.urls')),
    path('checkout/', include('checkout.urls')),
    path('review/', include('review.urls')),
    path('auth/', include('authentication.urls')),
]

book/urls.py
from django.urls import path
from main.views import show_main
from book.views import get_books

app_name = "book"
urlpatterns = [
    path("", get_books, name="get_books"),
]

review/urls.py
from django.urls import path
from . import views

app_name = 'review'

urlpatterns = [
    path('<str:book_id>/', views.review_list, name='review_list'),
    path('<str:book_id>/add/', views.add_review, name='add_review'),
    path('api/<str:book_id>/get/', views.get_review_api, name='get_review_api'),
    path('api/<str:book_id>/post/review/', views.post_review_api, name='post_review_api'),
]

review/models.py
from django.db import models
from django.contrib.auth.models import User

from book.models import Book

class Review(models.Model):
    text = models.TextField()
    rating = models.IntegerField()
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    reviewer = models.ForeignKey(User, on_delete=models.CASCADE)

review/forms.py
from django import forms

from review.models import Review


RATING_CHOICES = ((1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5"),)

class ReviewForm(forms.ModelForm):

    class Meta:
        model = Review
        fields = ('text', 'rating', 'book', 'reviewer')
        widgets = {
            'text': forms.Textarea(attrs={'type' : 'text', 'placeholder' : 'Masukkan Teks Review', 'class' : 'form-text-control', 'autocomplete' : 'off'}),
            'rating': forms.RadioSelect(choices=RATING_CHOICES),
            'book' : forms.HiddenInput(),
            'reviewer' : forms.HiddenInput(),
        }

review/views.py
from django.shortcuts import render
from django.http import Http404, JsonResponse
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.models import User
from .forms import ReviewForm
from book.models import Book
from .models import Review

import json

@login_required(login_url='/login')
def add_review(request, book_id):

    if request.method == 'POST':
        form = ReviewForm(request.POST)

        if form.is_valid():
            review = form.save()
            
            return JsonResponse({'status': 'success', 'message': 'Review berhasil disimpan', 
                                 'review_rating': review.rating,
                                 "review_reviewer" : str(review.reviewer),
                                 "review_text" : review.text,
            })
    
    return JsonResponse({'status': 'error', 'message': 'Permintaan tidak valid'})

@login_required(login_url='/login')
def review_list(request, book_id):

    # Get book Object (if there is any)
    book = Book.objects.filter(id=book_id)

    if not book:
        raise Http404
    
    book = book.first()

    # Initiate Form Review

    form = ReviewForm(None, initial={
        'book' : book_id,
        'reviewer': request.user.id,
    })

    # Get all review objects
    reviews = Review.objects.filter(book=book)
    return render(request, 'review.html', {
        'form': form, 
        'book_id': book_id,
        'book' : book,
        'reviews' : reviews,
        'rating_range' : range(1, 6),
    })

def get_review_api(request,book_id):
     # Get book Object (if there is any)
    book = Book.objects.filter(id=book_id)

    if not book:
        raise Http404
    
    book = book.first()

    # Get all review objects
    reviews = Review.objects.filter(book=book)
    data = [
        {
            "pk" : book.pk,
            "fields" : {
                "title" : book.title,
                "publishedDate" : book.publishedDate,
                "price" : book.price,
                "imgUrl" : book.imgUrl,
                "stars" : book.stars,
                "category_name" : book.category_name,
                "author" : book.author,
                "reviews": []
            },
        }
    ]

    for review in reviews:
        data[0]["fields"]["reviews"].append({
            "pk" : review.pk,
            "fields" : {
                "text" : review.text,
                "rating" : review.rating,
                "book" : review.book.title,
                "reviewer" : review.reviewer.username,
            },
        })
    return JsonResponse(data,safe=False)

@csrf_exempt
def post_review_api(request,book_id):
    # Get book Object (if there is any)
    book = Book.objects.filter(id=book_id)

    if not book:
        raise Http404
    
    book = book.first()

    if request.method == 'POST':

        data = json.loads(request.body.decode('utf-8'))

        text = data.get("text")
        rating = data.get("rating")
        user_id = data.get("user_id")

        user = User.objects.get(pk=user_id)
        
        review = Review.objects.create(text=text, rating=rating, book=book, reviewer=user)

        return JsonResponse({'status': 'success', 'message': 'Review berhasil disimpan', 
                                'review_rating': review.rating,
                                "review_reviewer" : str(review.reviewer),
                                "review_text" : review.text,
        })
    
    return JsonResponse({'status': 'error', 'message': 'Permintaan tidak valid'})

review/templates/review.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<head>
    <title>Halaman Review</title>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <style>
        /* CSS untuk gaya modal pop-up */
        .modal {
            display: none;
            position: fixed;
            z-index: 1;
            left: 0;
            top: 0;
            width: 100%;
            height: 100%;
            background-color: rgba(0,0,0,0.7);
        }
        .modal-content {
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            background-color: #fff;
            padding: 20px;
            border-radius: 5px;
            
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
        }
        .five-pointed-star {
            --star-color:gray;
            margin:1em auto;
            font-size:1em;
            position: relative;
            display: block;
            width: 0px;
            height: 0px;
            border-right: 1em solid transparent;
            border-bottom: 0.7em solid var(--star-color);
            border-left: 1em solid transparent;
            transform: rotate(35deg);
        }
        .five-pointed-star:before {
            border-bottom: 0.8em solid var(--star-color);
            border-left: 0.3em solid transparent;
            border-right: 0.3em solid transparent;
            position: absolute;
            height: 0;
            width: 0;
            top: -0.45em;
            left: -0.65em;
            display: block;
            content:"";
            transform: rotate(-35deg);
        }
        .five-pointed-star:after {
            position: absolute;
            display: block;
            top: 0.03em;
            left: -1.05em;
            width: 0;
            height: 0;
            border-right: 1em solid transparent;
            border-bottom: 0.7em solid var(--star-color);
            border-left: 1em solid transparent;
            transform: rotate(-70deg);
            content:"";
        }

        #review-container {
            display: flex;
            flex-direction: row;
            flex-wrap: nowrap;
            overflow-x: auto;
            width: 100%;
            margin: 1em 0;
        }

        .review {
            display: flex;
            flex-direction: column;
            flex-shrink : 0;
            border: 1px solid black;
            box-shadow: 6px 6px 6px 4px rgba(0,0,0,0.3);
            padding: 0.7em 1.25em;
            border-radius: 1em;
            margin: 0em 0.5em;

            width: 15em;
            height: 9em;
        }

        .review strong {
            color: #74B666;
            font-size: 1.5em;
        }

        .review p {
            margin: 0.5em 0;
            padding: 0;
            overflow-y: auto;
        }

        .review .five-pointed-star {
            font-size: 0.7em;
        }

        .button {
            padding: 0.5em 3em;
            border-radius: 1em;
            color: white;
            background-color: #74B666;
            margin: 0.25em 0.5em;
        }
    </style>
{% endblock meta %}
{% block content %}
<body>

    <div style="display: flex; flex-direction: column; align-items: center; padding: 4em 4em; width: min(1200px, 95vw); margin: auto; box-shadow: 6px 6px 6px 6px rgba(0,0,0,0.3); border-radius: 1em; position: relative; overflow: hidden;">

        <div style="display: flex; align-items: flex-start; width: 100%;">
            <img src="{{ book.imgUrl }}" style="padding: 0em 1.5em;"/>
            <div style="display: flex; flex-direction: column; color: #74B666;">
                <strong>{{ book.title }}</strong>
                <span>Penulis: {{ book.author }}</span>
                <span>Tanggal Rilis: {{ book.publishedDate }}</span>
                <span>Rating: {{ book.stars }}</span>
                <span>Kategori: {{ book.category_name }}</span>
            </div>
        </div>
        
        <div id="review-container">
            {% for review in reviews %}
                <div class="review">
                    <strong>{{ review.reviewer }}</strong>
                    <p>{{ review.text }}</p>
                    <div style="display: flex; justify-content: flex-start; width: 5em;">
                        {% for i in rating_range %}
                            {% if i <= review.rating %}
                                <div class="five-pointed-star" style="--star-color: #74B666;"></div>
                            {% else %}
                                <div class="five-pointed-star" style="--star-color: gray;"></div>
                            {% endif %}
                        {% endfor %}
                    </div>
                </div>
            {% endfor %}
        </div>

        <p>Kami sangat ingin mendengar pendapat Anda tentang<br>buku ini. Maukah Anda memberikan ulasan?</p>

        <button id="reviewButton" class="button">Review</button>

        <span style="height: 3em;"></span>

        <div style="position: absolute; bottom:0; left:0; right:0; height: 3em; background-color: #74B666;"></div>

    </div>

    <!-- Modal Pop-up -->
    <div id="reviewModal" class="modal">
        <div class="modal-content" style="width: 30em; position: relative; overflow: hidden;">
            <form id="reviewForm">
                {% csrf_token %}
                
                {{ form.text }}
                {{ form.text.errors }}

                <div style="display: flex; width: 20em;">
                    {% for radio in form.rating %}
                        <label class="five-pointed-star" for="{{ radio.id_for_label }}">
                            <span class="radio" style="display: none;">{{ radio.tag }}</span>
                        </label>
                    {% endfor %}
                </div>
                
                {{ form.rating.errors }}

                {{ form.book }}
                {{ form.book.errors }}

                {{ form.reviewer }}
                {{ form.reviewer.errors }}

                <div style="display: flex; justify-content: center;">
                    <button id="postReview" type="submit" class="button">Post</button>
                    <button id="backReview" type="button" class="button">Back</button>
                </div>
                
            </form>

            <span style="height: 2.5em;"></span>

            <div style="position: absolute; bottom:0; left:0; right:0; height: 2.5em; background-color: #74B666;"></div>
        </div>
    </div>

    <script>
        $(document).ready(function() {
            // Tampilkan pop-up saat tombol "Review" ditekan
            $("#reviewButton").click(function() {
                $("#reviewModal").show();
            });

            $("#backReview").click(function() {
                $("#reviewModal").hide();
            });

            // Tangani submit form dengan Ajax
            $("#reviewForm").submit(function(e) {
                e.preventDefault();
                $.ajax({
                    type: "POST",
                    url: "{% url 'review:add_review' book_id %}",
                    headers: {'X-CSRFToken': $("input[name=csrfmiddlewaretoken]").val()},
                    data: {
                        text: $("#id_text").val(),
                        rating: $("input[name='rating']:checked").val(),
                        book: $("#id_book").val(),
                        reviewer: $("#id_reviewer").val(),
                    },
                    success: function(response) {
                        if (response.status === 'success') {
                            $("#reviewModal").hide();

                            let result = '<div class="review">'
                            + '<strong>' + response.review_reviewer + '</strong>'
                            + '<p>' + response.review_text + '</p>';

                            result += '<div style="display: flex; justify-content: flex-start; width: 5em;">';

                            for (let i=1; i<6; i++) {
                                if (i <= response.review_rating) {
                                    result += '<div class="five-pointed-star" style="--star-color: #74B666;"></div>';
                                } else {
                                    result += '<div class="five-pointed-star" style="--star-color: gray;"></div>';
                                }
                            }

                            result += '</div>';

                            $("#review-container").append(result)
                        } else {
                            alert("Terjadi kesalahan: " + response.message);
                        }
                    },
                    error: function() {
                        alert("Terjadi kesalahan dalam mengirim permintaan.");
                    }
                });
            });
        });


        $(".five-pointed-star .radio input").on("change", function() {
            let rating_id_text = $(this).attr("id").slice(0, -1);
            let rating_id_number = $(this).attr("id").slice(-1);
            
            for (let i = 0; i <= 4; i++) {
                let star = $("label[for=" + rating_id_text + i + "]");
                if (i <= parseInt(rating_id_number)) {
                    star.css("--star-color", "#74B666");
                } else {
                    star.css("--star-color", "gray");
                }
                
            }
        });
    </script>
</body>
{% endblock %}